# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20161106_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to='movies/static/movies/images/'),
        ),
    ]
