# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20161106_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to='static/movies/images'),
        ),
    ]
