# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20161107_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.CharField(default='0 min', max_length=10),
        ),
    ]
