# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_rating'),
        ('movies', '0015_auto_20161117_1604'),
    ]

    operations = [
    ]
