# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-12 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default='5', max_digits=3),
        ),
    ]
